---
- [[move,a0,n00],   [move,a1,n21],                   ]
- [[pick,a0,n00,b0],[move,a1,n20],      [move,a2,n11]]
- [[move,a0,n10],   [pick,a1,n20,b4],   [move,a2,n01]]
- [[move,a0,n11],                       [pick,a2,n01,b1]]
- [                 [move,a1,n10]]
- [                 [move,a1,n00]]
- [[move,a0,n10],   [drop,a1,n00,b4]]
- [[move,a0,n20],                       [move,a2,n11]]
- [[move,a0,n30],   [move,a1,n10],      [move,a2,n12]]
- [[drop,a0,n30,b0],[move,a1,n11]]
